### ISSUE TITLE
sendTransaction privateFor failed with Status:400 Bad Request

### ISSUE THREAD

**Issue by SebLKMa** [Szkered/quorum-raft-cluster#5]
I created just 2 very nodes in same machine by following all steps.
My static-nodes.json was hardcoded with  the following:
["enode://d1648eb7d052e165287af5cc3608ebb1bdf5117a7a75c75b40b4213f9c0c57abcf44ae6247401e5482ea6f89e87887be538624eb9a000a1d5f1b2d8c8b19b3fd@192.168.9.133:21000?discport=0&raftport=23000",
"enode://4f0a577f59edc03e1e712b4fd8429ea807190698b2232e8a5ff45e7234ba8d895fd1def1682a33d44a6beb498125e3d1c169d710e0287ebd577e9f6fb24f410b@192.168.9.133:21002?discport=0&raftport=23002"]

admin.peers was ok with:
> admin.peers
[{
    caps: ["eth/63"],
    id: "4f0a577f59edc03e1e712b4fd8429ea807190698b2232e8a5ff45e7234ba8d895fd1def1682a33d44a6beb498125e3d1c169d710e0287ebd577e9f6fb24f410b",
    name: "Geth/v1.7.2-stable-ee498061/linux-amd64/go1.7.3",
    network: {
      localAddress: "192.168.9.133:57688",
      remoteAddress: "192.168.9.133:21002"

But testing sendTransaction with privateFor failed with Status:400 Bad Request
> eth.sendTransaction({from:eth.accounts[0]})
"0x7856e07c4ddcf1ae8e97562b723870a2eb114eace612c19c807de067a9162df9"
> eth.sendTransaction({from:eth.accounts[0], privateFor:["0IkCnlZq1Bgv37NibMiMxvL9RrcTcIGzmGiyYuRlFyc="]})
Error: Non-200 status code: &{Status:400 Bad Request StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 27 Feb 2018 19:03:42 GMT] Server:[Warp/3.2.12]] Body:0xc421e05b40 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc421f55590 TLS:<nil>}
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

Hope you can shed some light.
-Seb

**Comment by SebLKMa** [comment]
I re-install constellation 0.3.2, re-built latest quorum from git clone today.
Now sendTransaction with privateFor returns hash as expected:
> eth.sendTransaction({from:eth.accounts[0]})
"0xf3baac9c7676eafe95f356bb2305b15fedfe383f505b3438d5c5729a0f8133e1"
> eth.sendTransaction({from:eth.accounts[0],privateFor:["atTB8MLoMHFmXbjgxn9o80QGIzQeP/vHiJSSOgf5cAU="]});
"0x287a87d3689e16ca098c3e2991b25ca0f53e35981f5ad163d7a203c96acc6f95"
