### ISSUE TITLE
Error while doing a private transaction

### ISSUE THREAD

**Issue by ksbachu** [Szkered/quorum-raft-cluster#6]
Hi @Szkered ,
We installed the 3 node setup as per you steps. It is great and working fine.
We an able to do public transactions and see the transactions hashes, block numbers.
But when we do the private transaction below error is coming. We struggled with multiple options and getting below error.

Error: Non-200 status code: &{Status:400 Bad Request StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Sun, 01 Apr 2018 12:27:40 GMT] Server:[Warp/3.2.12]] Body:0xc4256f6e80 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc425eccff0 TLS:<nil>}
    at Object.InvalidResponse (/Users/sbachu/Documents/Demo/bcDemo/node_modules/web3/lib/web3/errors.js:38:16)
    at /Users/sbachu/Documents/Demo/bcDemo/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/Users/sbachu/Documents/Demo/bcDemo/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/sbachu/Documents/Demo/bcDemo/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)

Please help us to move forward.

**Comment by zekun-shi** [comment]
it seems like your constellation cluster is not properly connected. Please share your OS info

**Comment by ksbachu** [comment]
Hi @Szkered ,
Thanks for the reply. Please find the OS information below,
OS: Ubuntu 16.04
RAM: 4GB
CPUs: 2
Hard Disk: 10GB
